//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shekel.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYC
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string DocumentNumber { get; set; }
        public string DocumentType { get; set; }
        public string SelfiePath { get; set; }
        public string DocumentPath { get; set; }
        public string OTP { get; set; }
        public string Status { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
