//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shekel.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShekelEntities : DbContext
    {
        public ShekelEntities()
            : base("name=ShekelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Bonus> Bonuses { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Investment> Investments { get; set; }
        public virtual DbSet<InvestmentSchedule> InvestmentSchedules { get; set; }
        public virtual DbSet<KYC> KYCs { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Referral> Referrals { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
