//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shekel.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public string TransactionID { get; set; }
        public string ExternalReference { get; set; }
        public string SourceUserID { get; set; }
        public string SourceEmail { get; set; }
        public string SourceTelephone { get; set; }
        public decimal SourceAmount { get; set; }
        public string SourceCurrency { get; set; }
        public decimal Fee { get; set; }
        public string FeeCurrency { get; set; }
        public string DestinationUserID { get; set; }
        public string DestinationEmail { get; set; }
        public string DestinationTelephone { get; set; }
        public decimal DestinationAmount { get; set; }
        public string DestinationCurrency { get; set; }
        public string TransactionType { get; set; }
        public string DescriptionEnglish { get; set; }
        public string PaymentReference { get; set; }
        public string Status { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public decimal RunningBalance { get; set; }
        public string Method { get; set; }
    }
}
