//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shekel.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string UserType { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> Age { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string Country { get; set; }
        public string Password { get; set; }
        public string LastPassword { get; set; }
        public System.DateTime LastLogin { get; set; }
        public int LoginAttempts { get; set; }
        public bool LockedOut { get; set; }
        public string ReferralCode { get; set; }
        public Nullable<bool> Verified { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNumber { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string DisplayName { get; set; }
    }
}
